# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  GLFW_config = debug
  application_config = debug

else ifeq ($(config),release)
  GLFW_config = release
  application_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := GLFW application

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C application/vendor/GLFW -f Makefile config=$(GLFW_config)
endif

application: GLFW
ifneq (,$(application_config))
	@echo "==== Building application ($(application_config)) ===="
	@${MAKE} --no-print-directory -C . -f application.make config=$(application_config)
endif

clean:
	@${MAKE} --no-print-directory -C application/vendor/GLFW -f Makefile clean
	@${MAKE} --no-print-directory -C . -f application.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   GLFW"
	@echo "   application"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"